baseURL = "https://hyunyoung2.github.io/my-note-for-cs224n-stanford/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "my note for CS224n of stanford"
theme = "docdock"
themesDir = "themes"
publishDir = "docs"

[params]
editURL = "https://github.com/hyunyoung2/my-note-for-cs224n-stanford/edit/master/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = true # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
# For my custom CSS
customCSS = ["css/ForYouTubeByHyun.css"]



[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i>My note for CS224n of stanford Github repo"
identifier = "ds"
url = "https://github.com/hyunyoung2/my-note-for-cs224n-stanford"
weight = 10


[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
